# Generated by Django 5.0.3 on 2024-05-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slapify_web_app', '0002_song_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
